Algoritmo "4k - menorIgualATres - Manzano"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson
// Descrição   : Elaborar um programa que efetue a leitura de um determinado
// valor inteiro, e efetue a sua apresentação, caso o valor não seja maior
// que três.
// Autor(a)    : Giovanna Karolline Menezes Ribeiro
// Data atual  : 28/03/2026
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Mostra o número digitado quando este for menor ou igual à três.")
escreval("")
escreval("Digite um número inteiro:")
leia(numero)
se numero <= 3 então
escreval("Seu número é",numero,".")
fimse

Fimalgoritmo